Gopkg.toml

Fix the operator-sdk version as v0.5.0 (Suggestion made from @odra )
```
[[constraint]]
name = "github.com/operator-framework/operator-sdk"
version = "=v0.5.0" #osdk_version_annotation
```
Shows that it is a good practice adopted to work with operator-sdk in order to avoid issues and or breakchanges that may occur because of the updates made in the master branch.

feat(good pratices) : Fix the operator-sdk version/branch to be used as v0.5.0

---

Makefile
README.adoc
deploy/operator.yaml
version/version.go

https://issues.jboss.org/browse/AEROGEAR-8863
* Create Makefile with commands for the operator
* Update Readme with
* Remove Kubernetes tool from pre-requirement and replace it for OC tool
* Make easer the test and use it
* Following the best practices
1. Run the commands described in the README 
```
| *Command*                     | *Description*
| `make deploy`                 | Create mobile-security-service namespace and deploy operator and roles`
| `make undeploy`               | Remove mobile-security-service namespace and undeploy operator and roles`
| `make deploy-app`             | Deploy Mobile Security Service in the project`
| `make undeploy-app`           | Undeploy Mobile Security Service in the project`
| `make build`                  | Build operator for development …
```

feat(automatization) : Create makefile (AEROGEAR-8863)

---

CHANGELOG.md
Makefile
README.adoc
deploy/operator.yaml

https://issues.jboss.org/browse/AEROGEAR-8789
- Update readme with the build and publish info
- Add changelog
- Update docker org to use the aerogear instead of my personal one
- Remove the role for developers since it is not working
- Adding a description of its supportability to make clear that it was developed in order to work with Kubernetes and OCP clusters. 
- Replacing the oc command for kubectl in order to keep this supportability.

feat(AEROGEAR-8789) : Updating Reading and initial poc docker version

---

Makefile
README.adoc
deploy/role.yaml
deploy/role_binding.yaml

https://issues.jboss.org/browse/AEROGEAR-8870
Allow developers to use the operator and install the Mobile Security Service when the system:admin installed it.
Users/developer should be able to use the Operator to create the Mobile Security Service App and Database in their namespaces, however, they should still not able to create the Operator. 
Creating specific roles.
1. Following the steps in the README
With the system:admin user:
- Run make deploy
- Run the following roles commands
```
$ oc create   rolebinding developer-mobile-security-service-operator   --role=mobile-security-service-operator   --user=developer
$ oc create   rolebinding developer-mobile-security-service --role=mobile-security-service   --user=developer
```
2. Login with the developer user
- Create a project `oc …

feat(role) : Add role to allow users create the project

---

Makefile

Fix error found in the tests
Do not stop the execution in the `make undeploy` when some error is faced 
If something goes wrong and some rule or actions is missing the command should try to clean all. 
Using the `-` in front of the command
1. Call the command `make undeploy` with the operator not deployed in the cluster. All commands should be called. 
```
$ make undeploy
Undeploy Mobile Security Service Operator:
kubectl delete -f deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservice_crd.yaml
Error from server (NotFound): error when deleting "deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservice_crd.yaml": customresourcedefinitions.apiextensions.k8s.io "mobilesecurityservices.mobile-security-service.aerogear.com" not found
make: [undeploy] Error 1 (ignored) …
```

fix(makefile): Undeploy commands do not stop when find errors

---

Makefile
README.adoc
deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservice_cr.yaml
deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservice_crd.yaml
deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservicedb_cr.yaml
deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservicedb_crd.yaml

https://issues.jboss.org/browse/AEROGEAR-8963
Change the operator - The App and DB should be created in the same namespace of the operator
- All will be installed in the admin view
- Just one MSS will be available by cluster
- Adding the fixed namespace to the CR
- By Creating new commands
- By updating the README
1. Run the command `make deploy-all`
2. Check that all will be installed in the same namespace as the following image.
3. Run the command `make undeploy-all`
4. Check that all recourses, roles and the namespace were removed.

feat(operator/services) : Install all in the same namespace (AEROGEAR-8963)

---

deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservice_cr.yaml
pkg/controller/mobilesecurityservice/deployments.go

https://issues.jboss.org/browse/AEROGEAR-8985
Use/Install the latest version of MSS by the Operator always
Operator should be capable of updating the MSS to a new version, when a new version of MSS is released.
- Using the ImagePullPolicy: corev1.PullAlways,
- Getting the images based in the master branch: "aerogear/mobile-security-service:lastest"
1. Run the command `make deploy-all`
2. Check that all will be installed in the same namespace as the following image.
* kubernetes implementation regards the image policy: https://github.com/kubernetes/api/blob/master/core/v1/types.go#L2031
* Currently, for Mobile Security Service the latest version is always published when some change is merged in the master.

feat(MSS) : Use/Install the latest version of MSS by the Operator always

---

Makefile
README.adoc

https://issues.jboss.org/browse/AEROGEAR-8994
- Add dev tag to allow build and publish tag for dev purpose only
- Add make command for dev build and publish
- Update Readme with the info
The dev changes do not impact the "prod" tag image
1. Run `make build-dev` and `publish-dev``
2. Ensure that the tag was built and published
3. Test it working by doing a full deploy (`make deploy-all`)

feat(dev) : Add dev tag to allow build and publish tag for dev purpose only (AEROGEAR-8994)

---

Makefile
README.adoc
deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservicebind_cr.yaml
deploy/role.yaml
deploy/role_binding.yaml
pkg/controller/add_mobilesecurityservicebind.go
pkg/controller/mobilesecurityservicebind/mobilesecurityservicebind_controller.go

https://issues.jboss.org/browse/AEROGEAR-8971
- Add a controller for Bind Operations
- Update Readme
- Improve make commands
This controller will be responsible to watch the CR created by the MDC and do the bind/unbind/re-bind actions
Following the command used to create the controller.
```
operator-sdk add controller --api-version=mobile-security-service.aerogear.com/v1alpha1  --kind=MobileSecurityServiceBind
```
* Bulding and publishing the dev-tag (make build-dev & make publish-dev)
* Update the operator.yaml to use the dev tag
* Update the clusterHost cnfig
* Run `make create-all`
* Check that all is working with success
* Check that the pod test bind was created.
* Run `make delete-all`
* Check that all was removed with success.

feat(Bind) : Add controller (AEROGEAR-8971)

---

README.adoc
deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservicebind_cr.yaml
pkg/apis/mobilesecurityservice/v1alpha1/mobilesecurityservicebind_types.go
pkg/controller/add_mobilesecurityservicebind.go
pkg/controller/mobilesecurityservice/controller.go
pkg/controller/mobilesecurityservice/helpers.go
pkg/controller/mobilesecurityservicebind/configmaps.go
pkg/controller/mobilesecurityservicebind/helpers.go
pkg/controller/mobilesecurityservicebind/mobilesecurityservicebind_controller.go
pkg/controller/mobilesecurityservicebind/watches.go

https://issues.jboss.org/browse/AEROGEAR-8912
- Impl logic to allow spec the labels and/or namespaces which should be watched by the BIND
- Impl logic to allow spec the label(key:value) to define that the app should be managed by the BIND. It means that the app/pod is "bind" to the service.
- Add info into README and improved it.
- Allow reducing the scope which should be watched by the bind in order to improve performance
- Allow the bind knows what app is managed or not by the MDC and should be part of the action to bind/unbind/rebind to MSS by the Operator
- Allow specific labels by the attributes in the CR. 
- Create specs in type api
- Impl controller to filter based on the specs defined.  
1. Build and publish the dev tag ( make build-dev and make publish-dev)
2. Setup your local …

feat(BIND) : Add spec and logic to filter by labels specified

---

Makefile

https://issues.jboss.org/browse/AEROGEAR-8988
Customize the make delete-all in order to not show log errors for the user
Following an example of the msg.
```
Deleting Mobile Security Service and Database:
kubectl delete -f deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservice_cr.yaml
Error from server (NotFound): error when deleting "deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservice_cr.yaml": the server could not find the requested resource (delete mobilesecurityservices.mobile-security-service.aerogear.com mobile-security-service-app)
make[1]: [delete-app] Error 1 (ignored)
kubectl delete -f deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservicedb_cr.yaml
Error from server (NotFound): error when deleting …
```

Customize the make delete-all in order to not show log errors for the user

---

README.adoc
deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservice_cr.yaml
deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservicebind_cr.yaml
deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservicedb_cr.yaml
pkg/apis/mobilesecurityservice/v1alpha1/mobilesecurityservice_types.go
pkg/apis/mobilesecurityservice/v1alpha1/mobilesecurityservicebind_types.go
pkg/controller/add_mobilesecurityservicebind.go
pkg/controller/mobilesecurityservice/configmaps.go
pkg/controller/mobilesecurityservice/controller.go
pkg/controller/mobilesecurityservice/helpers.go
pkg/controller/mobilesecurityservicebind/configmaps.go
pkg/controller/mobilesecurityservicebind/helpers.go
pkg/controller/mobilesecurityservicebind/mobilesecurityservicebind_controller.go
pkg/models/sdkConfig.go

- https://issues.jboss.org/browse/AEROGEAR-9044
- Make the name of the configMap can be specified
- Also improvements in the route/ingress name
- Update README with the info
- Users should be able to specify it
- Make easier to use 
1. Build and publish the dev version
2. Run make create-all to install the dev image
3. Check that the configMap will be created and used by the APP and DB with the specified name
4. Check if the route still be created with success and is working.

Aerogear 9044 - Make the name of the configMap can be specified

---

README.adoc
deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservice_cr.yaml
deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservicebind_cr.yaml
deploy/operator.yaml
pkg/apis/mobilesecurityservice/v1alpha1/mobilesecurityservice_types.go
pkg/apis/mobilesecurityservice/v1alpha1/mobilesecurityservicebind_types.go
pkg/controller/mobilesecurityservice/controller.go
pkg/controller/mobilesecurityservice/helpers.go
pkg/controller/mobilesecurityservice/ingress.go
pkg/controller/mobilesecurityservicebind/configmaps.go
pkg/controller/mobilesecurityservicebind/helpers.go
pkg/controller/mobilesecurityservicebind/mobilesecurityservicebind_controller.go
pkg/controller/mobilesecurityservicebind/watches.go
pkg/controller/mobilesecurityservicedb/controller.go
pkg/controller/mobilesecurityservicedb/helpers.go
pkg/models/configService.go
pkg/models/sdkConfig.go
pkg/models/sdkConfigService.go
pkg/utils/utils.go

* https://issues.jboss.org/browse/AEROGEAR-9041
* https://issues.jboss.org/browse/AEROGEAR-8993
- Make the protocol (HTTP or HTTPS) be configured by the spec
- Create ConfigMap for the Bind app in the Cluster
- Make ConfigMap be created in the spec used in the SDK 
- Improve logs 
- Users should be able to get the JSON to config the SDK by the configMap
- Users should be able to define the cluster protocol 
- Easier to monitor and check what is happing
* Build and Publish the operator dev tag (`make build-dev and make publish-dev`)
* Config the CRS with the local clusterHost
* Install the operator by the command `make create-all`
* Create a new namespace/project to test the changes (E.g `$ oc new-project managemdc `)
* Create an app with the required labels:
* Check that the configMap …

feat(bind) : Creating configMap for the pods and removing fixed protocol

---

pkg/controller/mobilesecurityservicebind/mobilesecurityservicebind_controller.go
pkg/models/app.go
pkg/utils/utils.go

https://issues.jboss.org/browse/AEROGEAR-8914
When the watch/monitor find out the app with the respective criteria then the binding should be called.
The apps should be created by the operator
Impl in the Bind Controller
1. Build, Publish and Config and install the dev tag of the operator
2. Create a new namespace/project ( oc new-project test )
3. By the OCP catalogue create an app with the labels which will tell for the Operator that the app is bind to the service. Following the image. 
4. Check via postman that the app was created with the app name and ID stored in the labels.

feat(Bind) : Creating new apps by REST API (AEROGEAR-8914)

---

README.adoc

Add info that it has not been tested in Kubernetes besides the fact of we are using ks8 and all should work well on it as well

doc(README) : Add important info regards supportability

---

README.adoc
deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservicedb_cr.yaml
pkg/apis/mobilesecurityservice/v1alpha1/mobilesecurityservicedb_types.go
pkg/controller/mobilesecurityservicedb/deployments.go
pkg/controller/mobilesecurityservicedb/helpers.go

* https://issues.jboss.org/browse/AEROGEAR-8962
* https://issues.jboss.org/browse/AEROGEAR-9042
* Setup it to use the RedHat image
* Make the parameters name be configurable by the DB CR spec
* Solve errors in the logs 
* update the readme with the info
* we should use the redhat image instead of the public one which is ensured by the company
* better user experience
* make the project more flexible and configurable each image/version defined some name for the default args for the database be created.
1. Build, publish, config and install the build-dev image. Update local env to use the dev image.
2. Install the operator and all ( make create-all )
3. Check if the database will be installed and get running with success
4. Check if service is running with success
5. Bind and unbind some …

Use RedHat image DB + update readme with its configurable infos + make the params can be specified by the spec

---

README.adoc
pkg/controller/mobilesecurityservicedb/controller.go

* https://github.com/aerogear/mobile-security-service-operator/pull/44
* upper the time to 10 instead of 5. 
* add info over operator scope and namespace to the readme
* has some scenarios that 5 seconds is not enough because it worked fine with the dev image but now with a new cluster has not.

Small adjustment - Upper the time to get the ConfigMap and add info in the README 

---

pkg/controller/mobilesecurityservice/deployments.go
pkg/controller/mobilesecurityservice/fetches.go
pkg/controller/mobilesecurityservicedb/deployments.go
pkg/controller/mobilesecurityservicedb/helpers.go

https://issues.jboss.org/browse/AEROGEAR-9093
* Fix the bug which was faced after a while because the DB was not founding the configMap with the values for env variables. 
* Improve and fix the probes for the DB and Service
Fix issues and probes to work with centos/redhat db image. 
Ensure that all places will be looking for the correct name.
1. Clone the project, set up the Minishift, set up the mobile-security-service CR with the master VIP.  
2. Use the dev image `cmacedo/mobile-security-service-operator:AEROGEAR-9093-dev`. For it updates the `operator.yaml` file with this value
3. Run `make create-all` and check if all will be started with success. Also, check if the DB env variables are getting the values from the config map created to share it `mss-config`
4. Leave the instance …

fix(AEROGEAR-9093) - Error: configmaps mss-config not found and Probes

---

.circleci/config.yml
Makefile
README.adoc

AEROGEAR-8955
Update Circle CI config to build and push images
Add CD
Add steps to Makefile and circle CI config for the building and pushing of images
**Verification has already been verified - as per below comment:**
```
I've just finished testing this on my local fork, and can verify the following:
- CI build step works as expected (see CI check in this PR to confirm)
- CI builds and releases a new image whenever changes are merged to master
- `master` image [here](https://cloud.docker.com/repository/docker/murchu/mobile-security-service-operator/tags) were built and deployed by CI
- CI builds and releases a new image with the version tag, ie `0.1.0`, and also an image with the `latest` tag also, if any pushed commit has a git tag attached
- - `0.1.0` and `latest` images …
```

feat(ci): adds image build and push to ci (AEROGEAR-8955)

---

deploy/operator.yaml

https://issues.jboss.org/browse/AEROGEAR-9130
Pull the images from quay.io instead of dockerhub
Image storage moved to quay.io registry
update image value in [operator.yaml](https://github.com/aerogear/mobile-security-service-operator/blob/master/deploy/operator.yaml#L20)
Install operator as per README and confirm in the openshift console that the image used is the quay.io image, and that there are no issues installing the operator related to being able to pull the image.
- [ x ] Code has been tested locally by PR requester
This is being changed to point to the master image for now as we don't have any released versions of the operator. After there are released versions of the operator this value should be updated to point to the image with the `latest` tag instead.

fix: update operator.yaml to pull images from quay.io

---

.circleci/config.yml

correct binary link
fix breaking change introduced & update operator-sdk version used for releases
Fix link to binary & update release builds to use same operator-sdk version as master builds
update circle ci config
Check master builds from CI work again

fix(CI): fixes operator-sdk binary used by CI

---

build/Dockerfile

Security vulnerabilities in base image used for operator image builds ([AEROGEAR-9143](https://issues.jboss.org/browse/AEROGEAR-9143))
Update base image
Address security vulnerabilites (1 high, 1 medium)
Update base image to one that is to be introduced in the next operator-sdk release.
Build and push image manually to quay.io & check that there are no security vulnerabilities detected by security check.
Note: I have already done this and the image tagged `master` [here](https://quay.io/repository/damienomurchu/mobile-security-service-operator?tab=tags) has been built with the latest suggested base image - note all security checks pass. (The other image tagged `6802273` was built from the commit #6802273 from master on `mobile-security-service-operator` repo and has the two mentioned …

fix(image): updates base image used for image builds (AEROGEAR-9143)

---

pkg/controller/mobilesecurityservicedb/controller.go

Fix to allow the DB works when the App Service is not deployed
The DB should still be working independently of the app 
1. Setup your local env to work with this PR and the image: `docker.io/cmacedo/mobile-security-service-operator:fix-db`
2. Run the command to install the oper and then just the db `make create-oper create-db-only`
3. Check that the database contained was created and working
4. Now run the command `make delete-all`
5. Run the command to install all `make create-all`
6. Check that all is working well  and that the ENV VAR values of the DB came from the configMap created by the APP
- [] TODO

fix(db) : Allow the DB works when the App Service is not deployed

---

pkg/controller/mobilesecurityservice/helpers.go

https://issues.jboss.org/browse/AEROGEAR-9153
See JIRA
See JIRA
Remove SAR config from OAuth Proxy config
1) Use image: docker.io/lfitzgerald/mobile-security-service-operator:dev-ag9153
2) Run `make create-all`
3) Verify: That the developer user can access the service
There is a previous pr where I've requested that the verify confirm that the developer user does not have access. Linked below

fix(oauth): allow users with no namespace access to log in

---

Makefile
README.adoc
deploy/cluster_role.yaml
deploy/cluster_role_binding.yaml
deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservice_cr.yaml
deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservicedb_cr.yaml
deploy/operator.yaml
deploy/service_account.yaml
pkg/controller/mobilesecurityserviceapp/controller.go
pkg/controller/mobilesecurityservicedb/controller.go
pkg/controller/mobilesecurityservicedb/helpers.go
pkg/utils/utils.go

https://issues.jboss.org/browse/AEROGEAR-9152
Where possible, removing hardcoded references to the operator namespace
Would be unable to deploy the operator in any namespace other than the one hardcoded
Removed where possible from the code
1. Config your local env with this PR and the image `docker.io/aerogear/mobile-security-service-operator:0.1.0-AG-9152`
2. Install all by `make create-all`
3. Check the operator is created in the mobile-security-service namespace
5. Check the service and db are provisioned successfully

fix(): Remove hardcoded namespace for the operator (AEROGEAR-9152)

---

Makefile
pkg/controller/mobilesecurityservice/controller.go
pkg/controller/mobilesecurityservice/fetches.go
pkg/controller/mobilesecurityservice/status.go
pkg/controller/mobilesecurityserviceapp/controller.go
pkg/controller/mobilesecurityserviceapp/fetches.go
pkg/controller/mobilesecurityserviceapp/finalizer.go
pkg/controller/mobilesecurityserviceapp/status.go
pkg/controller/mobilesecurityservicedb/controller.go
pkg/controller/mobilesecurityservicedb/fetches.go
pkg/controller/mobilesecurityservicedb/status.go

https://issues.jboss.org/browse/AEROGEAR-9169
- Add export app namespace and remove unnecessary commands
- Refectory controller/reconcile code and fetch instances before updates in order to avoid issues regards the CR be already changed
**Explanation**
Logs as `Failed to update Status for the Component .... the object has been modified; please apply your changes to the latest version and try again"}` are faced because when the client will update the CR it was already changed. It is like when we go by the OCP UI and try to edit the YAML file of one CR which was changed between the time that the page was rendered and our click on the save button. 
- Try to avoid the above log issues
- Make easier troubleshooting and follow the logs.
- Make easier to keep the project maintained and allow it …

Refectory controller/reconcile code and fetch instances before updates in order to avoid issues regards the CR be already changed

---

pkg/controller/mobilesecurityservice/configmaps.go
pkg/controller/mobilesecurityservice/deployments.go
pkg/controller/mobilesecurityservice/route.go
pkg/controller/mobilesecurityservice/services.go
pkg/controller/mobilesecurityserviceapp/configmaps.go
pkg/controller/mobilesecurityservicedb/pvs.go
pkg/controller/mobilesecurityservicedb/services.go

Remove
Remove metav1.TypeMeta which is not required in the objects
Following good practices and do not add implicit and unnecessary info.
Use the image `docker.io/cmacedo/mobile-security-service-operator:REF` to install the operator and check that will still be working fine.

fix(refec) - Remove metav1.TypeMeta which is not required in the objects

---

Makefile

Local tests
Fix Makefile to use the var for the operator namespace.
- Use this PR to run make-create and make-delete. 
- Ensure that all be created with success.

fix(Makefile) : Use var for the operator namespace

---

pkg/controller/mobilesecurityservice/controller.go
pkg/controller/mobilesecurityservice/status.go
pkg/controller/mobilesecurityserviceapp/status.go
pkg/controller/mobilesecurityservicedb/status.go

Comments raised in another PR by @craicoverflow 
Remove deep equals check when the conditional is just to check the name "string"
- Good practice
- Better performance
1. Install the operator by using the image `docker.io/cmacedo/mobile-security-service-operator:REF-STATUS`
2. Run `make create-all`
3. Check if all were installed with success and if the MSS and MSS BD CR has the status fields filled

ref(update status) : not required use deep equals to compare the names

---

Gopkg.lock
pkg/controller/mobilesecurityservice/controller.go
pkg/controller/mobilesecurityservice/controller_test.go
pkg/controller/mobilesecurityservice/status.go
pkg/controller/mobilesecurityservice/status_test.go
pkg/controller/mobilesecurityservice/watches.go

https://issues.jboss.org/browse/AEROGEAR-8950
Added unit tests to cover the `mobilesecurityservice` package. Reached 73.6% code coverage.
Unit tests ensure that the code is fully tested and work as expected.
1. Referred to Operator SDK [documentation](https://github.com/operator-framework/operator-sdk/blob/master/doc/user/unit-testing.md)
2. Referred to [Operator SDK samples](https://github.com/operator-framework/operator-sdk-samples).
1. Run `make test`
2. Do the tests pass?
3. Confirm that the CircleCI build is passing: https://circleci.com/gh/aerogear/mobile-security-service-operator.

test(mobilesecurityservice): add test to package (AEROGEAR-8950)

---

pkg/controller/mobilesecurityservice/controller.go
pkg/controller/mobilesecurityservice/controller_test.go
pkg/controller/mobilesecurityservice/fetches.go
pkg/controller/mobilesecurityservice/route.go
pkg/controller/mobilesecurityservice/services.go
pkg/controller/mobilesecurityservice/status.go
pkg/controller/mobilesecurityservice/status_test.go
pkg/controller/mobilesecurityserviceapp/controller.go
pkg/controller/mobilesecurityserviceapp/fetches.go
pkg/controller/mobilesecurityserviceapp/finalizer.go
pkg/controller/mobilesecurityserviceapp/helpers.go
pkg/controller/mobilesecurityserviceapp/status.go
pkg/controller/mobilesecurityservicedb/controller.go
pkg/service/client.go
pkg/service/utils.go
pkg/utils/utils.go

[JIRA Comment](https://issues.jboss.org/browse/AEROGEAR-8987?focusedCommentId=13732533&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13732533)
Please note there are some changes here to the creation and deletion logic. These can be removed based on the other changes being made by @camilamacedo86 in another pr.
An additional Service is added by the operator which is not fronted by a Route to be used by the operator in order to interact with the service as required by the consumption pr.
1. Using this image: `quay.io/laurafitzgerald/mobile-security-service-operator:0.1.0-dev-ag8987-2` 
2. Run `make create-all`
3. Verify access to the server and additionally that the make delete and update of apps is working correctly.
a) a new Service is created titled …

fix(oauth): allow server access to the operator

---

pkg/controller/mobilesecurityservice/controller_test.go
pkg/controller/mobilesecurityservice/status_test.go
pkg/controller/mobilesecurityservicedb/controller_test.go
pkg/controller/mobilesecurityservicedb/status_test.go
pkg/controller/mobilesecurityservicedb/test_mocks.go

https://issues.jboss.org/browse/AEROGEAR-8952
Added unit tests to cover the `mobilesecurityservicedb` package. Coverage for this package is at 73%.
Unit tests ensure that the code is fully tested and work as expected.
1. Referred to Operator SDK [documentation](https://github.com/operator-framework/operator-sdk/blob/master/doc/user/unit-testing.md)
2. Referred to [Operator SDK samples](https://github.com/operator-framework/operator-sdk-samples).
1. Run `make test`
2. Do the tests pass?
3. Confirm that the CircleCI build is passing: https://circleci.com/gh/aerogear/mobile-security-service-operator.

test(mobilesecurityservice): add unit tests for the database package (AEROGEAR-8952)

---

Makefile
README.adoc
deploy/service_account.yaml
pkg/controller/mobilesecurityservice/controller.go
pkg/controller/mobilesecurityservice/controller_test.go
pkg/controller/mobilesecurityservice/deployments.go
pkg/controller/mobilesecurityservice/fetches.go
pkg/controller/mobilesecurityservice/helpers.go
pkg/controller/mobilesecurityservice/serviceaccount.go
pkg/controller/mobilesecurityservice/watches.go

https://issues.jboss.org/browse/AEROGEAR-9154
$title
More specific access control
Add the additional Service Account
Reference it from the Deployment and OAuth config
1) Use image:  quay.io/laurafitzgerald/mobile-security-service-operator:0.1.0-dev-ag9154
2) Run `make create-all`
3) Verify
a) That there is a ServiceAccount called `mobile-security-service` which contains the required redirect annotation
b) That there is a ServiceAccount entry with the value `mobile-security-service` in the app Deployment Config
c) That the new SericeAccount `mobile-security-service` is passed to the OAuth container args in the Deployment Config
d) That the OAuth Service works correctly by navigating to the route and authenticating using OAuth which should allow you to view the Application.
A note on …

fix(oauth): add seperate service account for oauth proxy

---

pkg/controller/mobilesecurityservice/helpers.go

https://issues.jboss.org/browse/AEROGEAR-9155
Randomising the OAuth proxy cookie secret. 
It was previously hardcoded to "SECRET" which could be used to decode all OAuth proxy cookies.
Introducing a helper method to return a random string.
1. Use the image quay.io/davidffrench/mobile-security-service-operator:0.1.0-AG-9155
2. Run `make create-all`
3. Verify you can log into the MSS admin UI.

feat(oauth): Randomising cookie secret (AEROGEAR-9155)

---

Makefile
README.adoc
cmd/manager/main.go
deploy/operator_service.yaml
deploy/service_monitor.yaml

https://issues.jboss.org/browse/INTLY-1455
enable metrics for the mobile-security-service-operator
Required functionality for a managed service
added a service monitor , and service and code to enable 
- start minishift as outline at https://github.com/aerogear/mobile-security-service-operator#minishift-installation-and-setup
- deploy the https://github.com/integr8ly/application-monitoring-operator 
- Note some Grafana and Prometheus images won't pull so change the image registry to `registry.access.redhat.com` to install
- clone this repo and checkout this branch
- `cd mobile-security-service-operator`
- change the operator image to point at dev this line https://github.com/aerogear/mobile-security-service-operator/blob/4b …

feat(add-metrics): add metrics to the operator :(INTLY-1455)

---

Makefile

https://issues.jboss.org/browse/AEROGEAR-9224
Remove mobile-security-service-app CRD first
Removing an app CRD, removes all instances of the CR. Removing an app CR requires the server to be up, so this needs to be deleted afterward.
1. Checkout this branch locally
2. Run `make create-all`. Wait for all to come up.
3. Run `make create-app-ns`
4. Run `make create-app`
5. Run `make delete-all`
6. Verify everything gets deleted and it does not get stuck

fix(make): Delete app CRD first (AEROGEAR-9224)

---

pkg/controller/mobilesecurityservice/controller.go
pkg/controller/mobilesecurityservice/status.go
pkg/controller/mobilesecurityserviceapp/controller.go
pkg/controller/mobilesecurityserviceapp/status.go
pkg/controller/mobilesecurityservicedb/controller.go
pkg/controller/mobilesecurityservicedb/status.go
pkg/utils/utils.go

https://issues.jboss.org/browse/AEROGEAR-9267
- Add Invalid status
-Make clear that the namespace is invalid
Use the image:   docker.io/cmacedo/mobile-security-service-operator:AEROGEAR-9267
1. Install the oper
2. create an app in a namespace that is not valid and check the Status of this resource
3. try to create the MSS in an invalid namespace and check the status of this resource
4. try to create the DB in an invalid namespace and check the status of this resource

feat(status) : Add Status when the CR was applied in an invalid namespace (AEROGEAR-9267)

---

pkg/controller/mobilesecurityserviceapp/controller_test.go
pkg/controller/mobilesecurityserviceapp/fakeclient_test.go
pkg/controller/mobilesecurityserviceapp/fetches.go
pkg/controller/mobilesecurityserviceapp/mocks_test.go
pkg/service/client.go

AEROGEAR-8951 
Add test coverage for app controller
Add test coverage
Add test coverage for methods in app controller
Confirm tests complete successfully:
- confirm tests run locally (`GOCACHE=off go test -cover github.com/aerogear/mobile-security-service-operator/pkg/controller/mobilesecurityserviceapp -v`)
- confirm tests are passing in CI in this PR
Confirm changes have not affected or broken the operator:

AEROGEAR-8951 - Service app controller tests

---

pkg/controller/mobilesecurityserviceapp/mocks_test.go
pkg/controller/mobilesecurityserviceapp/status_test.go
pkg/controller/mobilesecurityserviceapp/validations.go
pkg/controller/mobilesecurityserviceapp/validations_test.go

AEROGEAR-8951 
Add test coverage for gaps in serviceapp pkg
Add test coverage
Add test coverage for gaps in serviceapp pkg
Confirm tests complete successfully:
- confirm tests run locally (`GOCACHE=off go test -cover github.com/aerogear/mobile-security-service-operator/pkg/controller/mobilesecurityserviceapp -v`)
- confirm tests are passing in CI in this PR

tests(serviceapp): adds validations.go coverage (AEROGEAR-8951)

---

Makefile
README.adoc
deploy/prometheus-rule.yaml

https://issues.jboss.org/browse/INTLY-1456
adds Alerts to be used in Integr8ly monitoring
Requirement for Integr8ly
yaml file with a custom resource and update docs. 
1. log on to this cluster https://master.waterford-9fb3.openshiftworkshop.com, credentials can be found on this [doc](https://docs.google.com/document/d/1EX9M9aiJFDJ61HAHtOi305OsNzbKX2EQXtRsf3EWO58)
2. Open the [Prometheus Alerts](https://prometheus-route-middleware-monitoring.apps.waterford-9fb3.openshiftworkshop.com/alerts) and check for the following alerts
3. In Openshift console go to the mobile-security-service project and scale down the operator pod.
4. Wait 5 minutes and check the Prometheus Alerts …

feat(alerts): Add Alerts be used by the integr8ly project(INTLY-1456)

---

README.adoc

fix minor issues in README
fix minor issues in README
fix minor issues in README
fix minor issues in README
Check README & verify changes are ok.

docs(README): minor corrections (AEROGEAR-9256)

---

.circleci/config.yml
Makefile
README.adoc
cmd/manager/main.go
pkg/controller/mobilesecurityserviceapp/controller.go

https://issues.jboss.org/browse/AEROGEAR-9223
- Refactor the commands to include 
-- An install/uninstall for the project
-- refresh-operator-image which gives us the ability to pull in a new image on the same tag without having to delete and create everything in order to test updated dev images.
-- syntax following category/command where appropriate
- Split the commands in the README to 3 tables
We've got a lot of commands in the Makefile, now that the project has progressed they needed a little refactor
See `What`
EDIT: Use this image for the operator test quay.io/laurafitzgerald/mobile-security-service-operator:0.1.0-dev-ag
1. Run `make install`
2. Verify that the operator and mss project are installed successfully
3. Run `make apply-example-app`
4. Verify the app cr is created and is …

make command refactor

---

pkg/controller/mobilesecurityservicedb/deployments.go

We should not set the TypeMeta
Remove the TypeMeta from the DB deployment
It is set automatically when the object is instanced 
- Check the CI.

fix(deployment): remove TypeMeta from db deployment

---

scripts/commit-filter-check.sh

Unable to use the commit hooks when the task is not tracked in the AEROGEAR
- Remove the check that makes be mandatory have the "AEROGEAR-*****" from the checks
For example, now we are doing tasks tracked in the integr8ly project for it. In this way, no make sense we have this check and in my pov, it has not been so helpful at all. 
- just remove the specify checks for it from the script called by the git hook
Do any git operation which will call it and do not add AEROGEAR in the msg
Following the test performed.

fix(script) : Remove AEROGEAR check from the commit msg

---

deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservice_cr.yaml
pkg/controller/mobilesecurityservice/mandatory_specs.go
version/version.go

https://issues.jboss.org/browse/INTLY-1890
Fix the version of mobile security service deployed by the operator for use in the integreatly installer
Fix the version of mobile security service deployed by the operator for use in the integreatly installer
See changes
Deploy the operator using the template cr
1. Run `make install`
2. Verify that the image used in the Mobile Security Service pod that is used is tag 0.1.0 
(Optionally) Deploy the operator using the example cr below to verify that the image overrides
Using image: `quay.io/laurafitzgerald/mobile-security-service-operator:intly-1890`
Follow steps 1. and 2. as above. 
Cr Example
```
apiVersion: mobile-security-service.aerogear.com/v1alpha1
kind: MobileSecurityService
metadata:
name: mobile-security-service
```

(fix)version: use 0.1.0 of mobile-security-service (INTLY-1890)

---

Makefile
README.adoc
deploy/monitor/mss_service_monitor.yaml

https://issues.jboss.org/browse/INTLY-1892
Add mobile security service metrics to Prometheus
Required to created alerts and dashboards
Add a Prometheus ServiceMonitor
- Its deployed here
https://prometheus-route-middleware-monitoring.apps.austin-3e02.openshiftworkshop.com/graph
- Check the following metrics exist 
- go_gc_duration_seconds{job="mobile-security-service-application"}
- go_gc_duration_seconds_count{job="mobile-security-service-application"}
- go_gc_duration_seconds_sum{job="mobile-security-service-application"}
- promhttp_metric_handler_requests_in_flight{job="mobile-security-service-application"}
- promhttp_metric_handler_requests_total{job="mobile-security-service-application"}

Intly 1892

---

pkg/service/client.go

The scenario was checked by running the app locally. 
Add validation for when the error faced when the service is called did not result in an HTTP response 
Avoid panic because the response is nil for example when debugging it locally. 
Check the CI

fix(log) : Add validation for when the error faced when the service is called did not result in an HTTP response 

---

README.adoc

- removing no required details info and keeping just the make command to install the monitoring
- fix the command info. 
Make clear what is required to do. 
IMHO: It had too much was making it be confusing. 
Keeping just the explanation over the command.
Check the changes in the README

fix(Readme) : removing no required details info

---

pkg/controller/mobilesecurityserviceapp/controller.go
pkg/utils/utils.go
pkg/utils/utils_test.go

https://issues.jboss.org/browse/AEROGEAR-9486 
Removed `/init` from the URL that is added to the SDKConfig
This is added by the JS-SDK. 
1. Replace the value for `template.spec.containers.image` with `quay.io/ephelan/mobile-security-service-operator:AEROGEAR-9486`
2. Run `make install`.
3. Run `make example-app/apply`.
4. Run `oc get cm example-appname-security -o json`. The value at `data.SDKConfig.url` should be the root URL, without an `/init` amended to it. Like this:
```sh
❯ oc get cm example-appname-security -o json                                                                                                                                 
{ …
```

fix(url): removed `/init` from URL

---

Makefile
deploy/monitor/mss_grafana_dashboard.yaml

https://issues.jboss.org/browse/INTLY-1895
add a grafana dashboard for monitoring on integr8ly
requirement for the service to be available on integr8ly
Add grafana dashboard for uptime, memory, cpu, and http requests 
Dashboard is deployed here 
https://grafana-route-middleware-monitoring.apps.austin-81cc.openshiftworkshop.com/d/_cxgpLnZx/mobile-security-service-application?refresh=10s&orgId=1&from=now-1d%2Fd&to=now-1d%2Fd

feat(grafana dashboard): Add grafana dashboard for uptime, memory, cpu, and http requests (INTLY-1895)

---

deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservice_cr.yaml

MDC interacts with MSS and expects HTTPS to be used.
Changed value of clusterProtocol from http to https.
As a developer I expect to use HTTPS. The CR should default to this protocol as it is far more likely to be used. This also means I as a developer do not need to modify the custom resource locally each time the MSS operator has been updated (and the CR is overwritten).

Make HTTPS the default protocol in the MobileSecurityService custom resource

---

pkg/service/client.go
pkg/utils/utils.go

https://issues.jboss.org/browse/AEROGEAR-9543
Make the operator use HTTP for all internal requests to the API.
If the cluster protocol in the MobileSecurityServiceCR is set to HTTPS then the operator will internally use HTTPS for API requests. This is causing the API requests that are made from the operator to fail and it prevents apps being created or fetched.
1. Update the image in `operator.yaml` to use the one created for verification to be `quay.io/ephelan/mobile-security-service-operator:AEROGEAR-9453`.
2. Ensure that the `clusterProtocol` value is "https" in [mobile-security-service_v1alpha1_mobilesecurityservice_cr.yaml](https://github.com/aerogear/mobile-security-service-operator/blob/bbab899a564fce811ac9ef1771b010 …

refactor: use HTTP for internal API requests (AEROGEAR-9543)

---

deploy/monitor/grafana_dashboard.yaml

current metric gives inconsistency when the time varys
change to more stable metric
consistency
use avg function
deployed here
https://grafana-route-middleware-monitoring.apps.dimitra-314f.openshiftworkshop.com/d/_cxgpLnZz/mobile-security-service-operator?refresh=10s&orgId=1

fix(change the metric): change the uptime metric to use avg (INTLY-**)

---

.circleci/config.yml
CHANGELOG.md
Gopkg.lock
Makefile
README.adoc
deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservicebackup_cr.yaml
deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservicebackup_crd.yaml
deploy/crds/mobilesecurityservice_v1alpha1_mobilesecurityservice_crd.yaml
deploy/crds/mobilesecurityservice_v1alpha1_mobilesecurityserviceapp_crd.yaml
deploy/crds/mobilesecurityservice_v1alpha1_mobilesecurityservicebackup_crd.yaml
deploy/crds/mobilesecurityservice_v1alpha1_mobilesecurityservicedb_crd.yaml
pkg/apis/mobilesecurityservice/v1alpha1/mobilesecurityservice_types.go
pkg/apis/mobilesecurityservice/v1alpha1/mobilesecurityserviceapp_types.go
pkg/apis/mobilesecurityservice/v1alpha1/mobilesecurityservicebackup_types.go
pkg/apis/mobilesecurityservice/v1alpha1/mobilesecurityservicedb_types.go
pkg/apis/mobilesecurityservice/v1alpha1/zz_generated.openapi.go
pkg/controller/mobilesecurityservice/helpers.go

https://issues.jboss.org/browse/AEROGEAR-9507
- Add OpenAPI Schema and definitions
- It will make easier create the OLM
- Following the good practices
- Make easier the understatement
- Validate the data in the CR by the API
* Check the CI
* Run the command `make setup` which will call the make code/gen which updates the files automatically.  
* if you wish you can test the operator again besides not be required since no impacts it should have. The image is: `docker.io/cmacedo/mobile-security-service-operator:openAPI`
* If you wish you can check how this validation works as follows. 
```yaml
apiVersion: mobile-security-service.aerogear.com/v1alpha1
kind: MobileSecurityService
metadata:
name: mobile-security-service
spec:
routeName: 1 # It will not be applied because there is expected a …
```

feat(OpenAPI) : Add schema validation and OpenAPI

---

CHANGELOG.md
SOP/SOP-mss.adoc
SOP/SOP-operator.adoc
deploy/monitor/mss_prometheus_rule.yaml
deploy/monitor/prometheus_rule.yaml

- https://issues.jboss.org/browse/INTLY-2709 ( raised after discussions over UPS SOP and Prometheus rules and the review over it)
- Remove the CLI steps from the SOP's
- Small fixes in the steps
- Fix the MobileSecurityServicePodCount ( it should alert when the pods are < 3 and NOT != of 3 )
- Fix the MobileSecurityServiceDown ( it was not working at all and shown the alert when the MSS pod was up and running )
- Add steps to scale the MSS pods in the case of some issues regards performance be faced.
- Add further information in order to attend the OPS suggestions/requirements
- Check the Sops [MMS](https://github.com/aerogear/mobile-security-service-operator/blob/3729f93bb71b836efd8ed6a25d1869231ef5339f/SOP/SOP-mss.adoc) and [Oper](https://github.com/aerogear/mobile-security-service-opera …

Fix prometheus rules and improve/fix the SOP

---

deploy/monitor/prometheus_rule.yaml

https://github.com/aerogear/mobile-security-service-operator/pull/151
The format with "" was causing issues and not render the alerts.
See here: https://prometheus-route-middleware-monitoring.apps.london-2f09.openshiftworkshop.com/alerts

fix(prometheus) : fix review suggestion which causes mal format issues

---

CHANGELOG.md
deploy/monitor/mss_grafana_dashboard.yaml

https://issues.jboss.org/browse/AEROGEAR-9714
Fix the following issue:
It is not getting the info over the app container. 
See the metric which should be used
Update the metrics o fix them
Use this JSON file in aa Grafana dashboard in an env which has all work as https://master.mdsdemo-710a.openshiftworkshop.com/console/project/middleware-monitoring/overview
Test performed here: https://grafana-route-middleware-monitoring.apps.mdsdemo-710a.openshiftworkshop.com/d/H6GQ0MvWz/mobile-security-service-application

Fix the chart `Mobile Security Service Application - Uptime` on Grafana application dashboard

---

CHANGELOG.md
deploy/monitor/mss_grafana_dashboard.yaml

https://issues.jboss.org/browse/AEROGEAR-9652
- Remove the CPU graph because we have no valid data to create this one
- Fix the Memory graph in order to create it over the service container and not operator one.
It is Service/Application Dashboard and should not use the operator data at all.
Check here the changes made applied manually: https://grafana-route-middleware-monitoring.apps.mdsdemo-710a.openshiftworkshop.com/d/H6GQ0MvWz/mobile-security-service-application

fix(Graphana Service Resources Dashboard)

---

CHANGELOG.md
deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservice_cr.yaml
deploy/crds/mobilesecurityservice_v1alpha1_mobilesecurityservice_crd.yaml
deploy/operator.yaml
pkg/apis/mobilesecurityservice/v1alpha1/mobilesecurityservice_types.go
pkg/apis/mobilesecurityservice/v1alpha1/zz_generated.openapi.go
pkg/controller/mobilesecurityservice/controller_test.go
pkg/controller/mobilesecurityservice/deployments.go
pkg/controller/mobilesecurityservice/mandatory_specs.go

https://issues.jboss.org/browse/AEROGEAR-9767
- Change/Add Memory and CPU resources requested and limits for MSS, Oauth and Operator
- Check the CI
- Use the image `cmacedo/mobile-security-service-operator:new` to install the MSS and check if the values defined in AEROGEAR-9767 are set up in its containers.

feat(resources) : Add resource requests/limits to MSS & MSS operator AEROGEAR-9767)

---

README.adoc

Hyperlink for CHANGELOG.md is pointing to incorrect location, fixed by pointing to correct location.

Fix hyperlink for CHANGELOG.md
