aerogear/mobile-security-service-operator

- README.adoc
Make the README clear and with all required information
Make a few improvements on it
> docs(Readme) : Improvements in the README

- README.adoc
fix(readme): Fix command description in readme
> fix(readme): Fix command description in readme

- README.adoc
- deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservice_cr.yaml
- pkg/apis/mobilesecurityservice/v1alpha1/mobilesecurityservice_types.go
- pkg/controller/mobilesecurityservice/controller.go
- pkg/controller/mobilesecurityservice/ingress.go
- pkg/controller/mobilesecurityservice/watches.go
- pkg/controller/mobilesecurityservicedb/controller.go
- pkg/controller/mobilesecurityservicedb/watches.go
https://issues.jboss.org/browse/AEROGEAR-8856
Add ingress/router for the service.
The operator full install the project
Using k8s Ingress in order to keep the Kubernetes support
Follow the steps in the README to install the operator and project and check that the router will be created with success. 
> feat(add ingress) - Add ingress/router for the service. (AEROGEAR-8856)

- README.adoc
- deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservice_cr.yaml
- deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservicedb_cr.yaml
- pkg/apis/mobilesecurityservice/v1alpha1/mobilesecurityservice_types.go
- pkg/controller/mobilesecurityservice/configmaps.go
- pkg/controller/mobilesecurityservice/helpers.go
- pkg/controller/mobilesecurityservice/ingress.go
- pkg/models/sdkConfig.go
- pkg/models/sdkConfigService.go
https://issues.jboss.org/browse/AEROGEAR-8808
Impl configMap created to have the SDK config with its JSON value/data.
1. Install the operator
2. Deploy operator and app ( make deploy and make deploy-app)
3. Check the configMaps created
4. The configmap *-sdk should show the JSON object.
> feat(sdk config) : Add sdk config result

- README.adoc
https://issues.jboss.org/browse/AEROGEAR-8788
Review and perform changes in the readme according to the team docs recommendations.
> doc(readme) : Review/Changes

- deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservice_cr.yaml
- pkg/controller/mobilesecurityservice/controller.go
https://github.com/aerogear/mobile-security-service-operator/pull/18
Fix branch image
Make the operator still able to get the latest version of the MSS
> fix(Image) : Fix branch image

- README.adoc
https://issues.jboss.org/browse/AEROGEAR-8988
- Improvements and add architecture def
Doc how to use and contribute with the project as it works. 
https://github.com/aerogear/mobile-security-service-operator/blob/89958204c3d437e8bcb43f40ae6398a62a9d5e6a/README.adoc
> feat(README) : Improvements and add architecture def (AEROGEAR-8988)

- deploy/operator.yaml
- pkg/controller/mobilesecurityservicebind/configmaps.go
- pkg/controller/mobilesecurityservicebind/mobilesecurityservicebind_controller.go
- pkg/models/app.go
- pkg/models/sdkConfigService.go
- pkg/utils/utils.go
- Publishing last dev changes after check that the operator was using dev image
- Ensure that the master branch is working well as should be.
> fix(lastChanges) : Publishing last dev changes after check that the operator was using dev image

- Makefile
- README.adoc
https://issues.jboss.org/browse/AEROGEAR-8972
* Ensure that the README is with all required info regards how the BIND works 
* Add in the Readme missing infos and doing a review on it
> docs(README): Add in the Readme missing infos and doing a review on it

- README.adoc
doc(README) : Fix some details into the README
Small fix and improvements into the README
> doc(README) : Fix some details into the README

- CHANGELOG.md
- pkg/controller/mobilesecurityservice/controller.go
- pkg/controller/mobilesecurityservice/fetches.go
- pkg/controller/mobilesecurityservice/watches.go
- pkg/controller/mobilesecurityservicebind/controller.go
- pkg/controller/mobilesecurityservicebind/fetches.go
- pkg/controller/mobilesecurityservicebind/helpers.go
- pkg/controller/mobilesecurityservicedb/controller.go
- pkg/controller/mobilesecurityservicedb/fetches.go
- pkg/controller/mobilesecurityserviceunbind/controller.go
- pkg/controller/mobilesecurityserviceunbind/fetches.go
- pkg/controller/mobilesecurityserviceunbind/helpers.go
Fulling test the operator
Improvement in the logs, check and fetches
Avoid issues and make easier to monitor the operator by logs
> fix(operator) : Small fix and improvements

- .circleci/config.yml
- Makefile
AEROGEAR-8954
Add Circle CI config to perform setup, test, and build checks
Add CI checks to repo
Add `.circleci/config.yml` file to repo 
Check that CI on this PR is passing by looking at bottom of page
> feat(ci): adds CI config to setup, test & build binary (AEROGEAR-8954)

- README.adoc
Small typo in git url in readme
> fix(readme): Typo in git url in readme

- Makefile
- README.adoc
Adding how to debug the project to the README
> doc(README) : Adding how to debug the project

- .circleci/config.yml
- README.adoc
- scripts/cleanup-coverage-file.sh
https://issues.jboss.org/browse/AEROGEAR-9078
Updates README with badges and new commands 
Badge-y goodness & add updated commands
Update README to render badge images & add updated commands to Makefile section of README
Check README and confirm CI passing badge is present, and also code coverage badge. Check Makefile reference section of README and confirm the `make build-x` and `make push-x` type commands are correct.
Note: code coverage value will be `unknown` as we don't have any test coverage at present.
> feat(CI): updates badges and commands in README

- deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservice_cr.yaml
https://issues.jboss.org/browse/AEROGEAR-9141
Just change the default setup config for the route name
> feat(route name) : Change the default spec/config parameter for route (AEROGEAR-9141)

- Makefile
Fix broken create-all command after name update
> fix(makefile): Fix broken command after name update

- README.adoc
https://issues.jboss.org/browse/INTLY-2031
Need verification steps as not sure what the outcome should will be after running the `make create-all` command
update the readme
to clarify the outcome of the installation .
Added verification steps
> Add verification readme

- .githooks/commit-msg
- .githooks/pre-commit
- Makefile
- pkg/apis/mobilesecurityservice/v1alpha1/mobilesecurityservice_types.go
- pkg/apis/mobilesecurityservice/v1alpha1/zz_generated.deepcopy.go
- pkg/controller/mobilesecurityservice/controller.go
- pkg/controller/mobilesecurityservice/controller_test.go
- pkg/controller/mobilesecurityservice/fakeclient_test.go
- pkg/controller/mobilesecurityservice/mocks_test.go
- pkg/controller/mobilesecurityservice/status.go
- pkg/controller/mobilesecurityservice/status_test.go
- pkg/controller/mobilesecurityserviceapp/controller.go
- pkg/controller/mobilesecurityserviceapp/status.go
- pkg/controller/mobilesecurityservicedb/controller.go
- pkg/controller/mobilesecurityservicedb/status.go
- pkg/utils/utils.go
- scripts/cleanup-coverage-file.sh
- scripts/code-check.sh
- scripts/export_local_envvars.sh
- A comment raised by a colleague across the teams. 
- https://github.com/aerogear/mobile-security-service-operator/pull/81
- https://issues.jboss.org/browse/AEROGEAR-9231
- https://issues.jboss.org/browse/AEROGEAR-9213
- https://issues.jboss.org/browse/AEROGEAR-9156
- Fix impl to update the status of the Services in the CR. (introduced at https://github.com/aerogear/mobile-security-service-operator/pull/81)
- Fix impl to create the values of the SDKConfigMap  (introduced at https://github.com/aerogear/mobile-security-service-operator/pull/81)
- Keep the reconcile calls centralized in the reconcile func in order to make the code more understandable, clean and follow the same standard proposed in the operator-framework docs and examples.
- NOT do the re-queue when an object is …
> Doing fixes and refacs in the code

- pkg/utils/utils_test.go
- pkg/utils/validations_test.go
https://issues.jboss.org/browse/AEROGEAR-9214
Added unit tests to cover the `utils` package. Coverage for this package is at 89%.
Unit tests ensure that the code is fully tested and work as expected.
1. Run `go test ./pkg/utils`
2. Do the tests pass?
3. Confirm that the CircleCI build is passing: https://circleci.com/gh/aerogear/mobile-security-service-operator.
> test(utils): Add unit tests (AEROGEAR-9214)

- pkg/controller/mobilesecurityservice/controller.go
- pkg/controller/mobilesecurityserviceapp/controller.go
- pkg/controller/mobilesecurityserviceapp/controller_test.go
- pkg/controller/mobilesecurityserviceapp/finalizer.go
- pkg/controller/mobilesecurityserviceapp/finalizer_test.go
- pkg/controller/mobilesecurityserviceapp/helpers.go
- pkg/controller/mobilesecurityservicedb/controller.go
- pkg/controller/mobilesecurityservicedb/controller_test.go
feedback from a red hatter architecture which has been using this project as an example. 
- Small improvements
- Fix some small issues that pass in the unit tests
Use the image docker.io/cmacedo/mobile-security-service-operator:IMP_FETCH and heck if the oper will be installed with success created/delete app
- `make create-all`
- `oc project mobile-security-service-apps`
- make create-app
- make delete-app
> refac(controller) : refac to make clean the code and more performative

- Gopkg.lock
- Makefile
- pkg/apis/mobilesecurityservice/v1alpha1/mobilesecurityservicedb_types.go
- pkg/controller/mobilesecurityserviceapp/mocks_test.go
- scripts/code-check.sh
https://issues.jboss.org/browse/AEROGEAR-9239
- Fix vet errors
- FIx pre-commit issues
- Remove errcheck since it is not working well with the framework impl. 
1. Clone this PR
2. Run `make setup-githooks`
3. Run `git commit --amend --no-edit`
> Fix pre-commit and vet errors(AEROGEAR-9239)

- deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservice_cr.yaml
- pkg/controller/mobilesecurityservice/mandatory_specs.go
update operator to use quay.io image for mobile-security-service
update operator to use quay.io image for mobile-security-service
mobile-security-service moving to quay.io
update image ref in cr file
Deploy operator, confirm it deploys correctly, and verify it is using quay.io image for mobile-security-service
> fix(image): updates operator to use quay.io mss image (AEROGEAR-9105)

- deploy/monitor/operator_service.yaml
Keep just the config in the files
Remove the data which is added/managed by the platform
Good practices and avoid pitful scenarios.
> fix(monitor) : config files

- deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservice_cr.yaml
- pkg/controller/mobilesecurityservice/mandatory_specs.go
https://issues.jboss.org/browse/AEROGEAR-9354
Use the latest tag created for MSS instead of the master one
The project should just use by default the latest release
Use the MobileSecurityServiceCR changed here to install the project and ensure that all still working on.
> feat(images) : Use the latest tag created for MSS instead of the master one

- CHANGELOG.md
https://issues.jboss.org/browse/AEROGEAR-9317
Just update the CHANGELOG.
> Changelog - First Release

- Makefile
- README.adoc
https://issues.jboss.org/browse/AEROGEAR-9381
- Add/update info to the README over how to do the releases
- Remove dev tag since it is no longer required
- Have this process doc
> feat(README) : Add info over how to do the releases (AEROGEAR-9381)

- Makefile
- README.adoc
- Add clear steps on how to check the installation
- Address a few comments/suggestions made before
- Imp readme.
> feat(Improvements) : Small improvements in the Readme and Makefile

- README.adoc
Add info that can be helpful to users/developers/admins. 
- Add db info over how to connect in the DB(Readme)
> doc(Readme): Add db info over how to connect in the DB

- pkg/controller/mobilesecurityservice/fetches.go
- pkg/controller/mobilesecurityserviceapp/controller.go
- pkg/controller/mobilesecurityserviceapp/fetches.go
Small refactory
- Add missing logs
- Add code to fetch the mss in the fetches.go.  file to centralize it. 
Check if the CI finishes with success
> refac(logs) : small refac in the logs and standard

- deploy/monitor/grafana-dashboard.yaml
https://issues.jboss.org/browse/INTLY-1895
Grafana dashboard 
for Integreatly monitoring of operator 
Added a yaml
Check the Grafana dashboard here https://grafana-route-middleware-monitoring.apps.austin-3e02.openshiftworkshop.com/d/_cxgpLnZz/mobile-security-service-operator?orgId=1&from=now%2Fd&to=now%2Fd
> feat(grafana-dashboard):grafana dashboard (INTLY-1458)

- SOP/SOP-mss.md
- SOP/SOP-operator.md
https://issues.jboss.org/browse/INTLY-1457
Create folder structure and files for adding the SOPs for the operator and mss
To prepare the location which can be tested by the alert links
Noting really required. Are the files there? Yes? Done.
> create SOP files

- pkg/controller/mobilesecurityservicedb/status.go
Issue found 
The ServiceStatus was not been updated. 
1. Check the CI
2. You can also use the image `docker.io/cmacedo/mobile-security-service-operator:serviceupdatefix
` to check that the status should be added in the Resource in the OCP.
> Small Fix  - fix(db) : status

- SOP/SOP-mss.md
- SOP/SOP-operator.md
https://issues.jboss.org/browse/INTLY-1894
Adding SOPs from doc
> adding operator sops

- deploy/monitor/mss_prometheus_rule.yaml
- deploy/monitor/prometheus_rule.yaml
> fix(fix sop url) : fix (INTLY-1983)

- deploy/monitor/mss_prometheus_rule.yaml
bug
incorrect sop_url
sop_url duplicated
remove extra url
visual verification url is updated
> fix(duplicate line): fix duplicate sop_url line (INTLY-1983)

- CHANGELOG.md
- README.adoc
- SOP/SOP-mss.adoc
- deploy/monitor/mss_prometheus_rule.yaml
- deploy/monitor/prometheus_rule.yaml
- version/version.go
https://issues.jboss.org/browse/AEROGEAR-9501
- Fix changelog and version
- Add info new release
Create a release with all that was achieved https://trello.com/b/mCiUFubz/security-service
> (release) : add changelog and version (AEROGEAR-9501)

- README.adoc
fix(Readme) : Fix URL regards build CI in the health status
> fix(Readme) : Fix URL regards build CI in the health status

- README.adoc
Add Design Pattern adopted to make easier the understanding. 
check the few lines added in the readme.
> doc(Readme) : Add the Design Pattern adopted

- SOP/SOP-mss.adoc
- SOP/SOP-operator.adoc
- https://issues.jboss.org/browse/INTLY-2727
- Chat with @Nanyte25 and e.g provided 
- See the [Oper SOP](https://github.com/aerogear/mobile-security-service-operator/blob/15301bff54f762f2f926c72d798472cdf2048796/SOP/SOP-operator.adoc)
- See the [MSS SOP](https://github.com/aerogear/mobile-security-service-operator/blob/15301bff54f762f2f926c72d798472cdf2048796/SOP/SOP-mss.adoc)
> feat(SOP) : Improvements requested by OPS

- CHANGELOG.md
- version/version.go
Once this is merged, I'll add a `0.3.0` tag.
> Update version and changelog for 0.3.0 release

- .circleci/config.yml
- CHANGELOG.md
- SOP/SOP-mss.adoc
- cmd/manager/main.go
- deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservice_cr.yaml
- deploy/monitor/mss_prometheus_rule.yaml
- deploy/monitor/prometheus_rule.yaml
- pkg/apis/mobilesecurityservice/v1alpha1/zz_generated.openapi.go
- pkg/controller/mobilesecurityservice/mandatory_specs.go
- version/version.go
- https://issues.jboss.org/browse/AEROGEAR-9746
- Release of new tag with the fixes/changes performed
- Upgrade the version of Mobile Security Service used by default from 0.1.0 to 0.2.1
> New release

- deploy/monitor/grafana_dashboard.yaml
- deploy/monitor/mss_grafana_dashboard.yaml
https://issues.jboss.org/browse/AEROGEAR-9676
Remove graphs with %
Check here: 
* (operator) : https://grafana-route-middleware-monitoring.apps.london-f408.open.redhat.com/d/_cxgpLnZz/mobile-security-service-operator?refresh=10s&orgId=1
* (app): https://grafana-route-middleware-monitoring.apps.london-f408.open.redhat.com/d/_cxgpLnZx/mobile-security-service-application?refresh=10s&orgId=1
Following what we are removing:
> feat(grafana) : remove % graphs (AEROGEAR-9676)

- CHANGELOG.md
- deploy/monitor/mss_prometheus_rule.yaml
- deploy/monitor/prometheus_rule.yaml
- version/version.go
https://issues.jboss.org/browse/AEROGEAR-9776
Release
> release 0.4.1
